In [5]:
import numpy as np
import pandas as pd
from scipy import stats

1. Calculate, theoretically (in your head is fine), the expected value for the average of 6 dice rolls.

In [6]:
die_distribution = stats.randint(1,7)
die_distribution.rvs(6).mean()

3.6666666666666665

2. Write the code necessary to simulate taking the average of 6 dice rolls 10,000 times. Store each of the 10,000 averages in a list.

In [27]:
n_simulations = 10_000
n_trials = 6

df = pd.DataFrame(np.random.choice(range(1,7), size=(n_simulations, n_trials)))
df

0  1  2  3  4  5
0     4  1  3  6  4  6
1     3  1  2  3  1  3
2     5  3  3  3  6  4
3     3  1  1  6  5  4
4     2  5  5  1  1  3
...  .. .. .. .. .. ..
9995  3  5  6  6  4  2
9996  5  5  1  6  2  3
9997  6  4  2  5  5  5
9998  1  2  6  2  5  2
9999  1  5  1  5  4  5

[10000 rows x 6 columns]

In [29]:
df["mean"] = df.mean(axis=1)
df

0  1  2  3  4  5      mean
0     4  1  3  6  4  6  4.000000
1     3  1  2  3  1  3  2.166667
2     5  3  3  3  6  4  4.000000
3     3  1  1  6  5  4  3.333333
4     2  5  5  1  1  3  2.833333
...  .. .. .. .. .. ..       ...
9995  3  5  6  6  4  2  4.333333
9996  5  5  1  6  2  3  3.666667
9997  6  4  2  5  5  5  4.500000
9998  1  2  6  2  5  2  3.000000
9999  1  5  1  5  4  5  3.500000

[10000 rows x 7 columns]

In [24]:
roll_means = []

for i in range(10_000):
    roll_mean = np.random.choice(range(1,7)).mean(axis=1)
    roll_means.append(roll_mean)

IndexError: tuple index out of range

In [22]:
roll_means

[array([3.66666667, 3.83333333, 2.66666667, ..., 2.16666667, 3.        ,
        3.83333333]),
 array([3.        , 4.66666667, 3.16666667, ..., 3.33333333, 3.33333333,
        3.16666667]),
 array([2.66666667, 3.83333333, 4.16666667, ..., 5.33333333, 2.66666667,
        3.83333333]),
 array([3.5       , 3.        , 3.16666667, ..., 3.16666667, 3.66666667,
        2.83333333]),
 array([3.33333333, 2.        , 4.        , ..., 2.16666667, 3.83333333,
        3.        ]),
 array([4.        , 2.33333333, 3.83333333, ..., 2.5       , 3.        ,
        3.33333333]),
 array([3.        , 2.83333333, 4.66666667, ..., 1.83333333, 3.83333333,
        3.83333333]),
 array([2.66666667, 2.5       , 3.        , ..., 2.83333333, 3.        ,
        5.33333333]),
 array([4.        , 2.66666667, 3.83333333, ..., 3.83333333, 4.16666667,
        3.66666667]),
 array([3.83333333, 4.        , 3.66666667, ..., 3.5       , 3.66666667,
        2.66666667]),
 array([3.        , 4.        , 4.16666667, ..., 3

3. Plot the distribution of the calculated averages. What do you notice? What kind of distribution is the underlying random variable (i.e. one dice roll?)

- Are the average grades in web development vs data science classes different?
- Is there a relationship between how early a student shows up to class and their grade?
- Are web dev or data science students more likely to be coffee drinkers?

$H_0$: the average grades between web dev and data sci are not different

$H_a$: the average grades between web dev and data sci are different

$H_0$: there is no relationship between how early a student shows up for class and their grade

$H_a$: there is a relationship between how early a student shows up for class and their grade

H0: web dev students are more likely to be coffee drinkers

H1: data sci students are more likely to be coffee drinkers

# Null hypothesis posits no change between the two groups