In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     1  5
1     3  5
2     3  5
3     1  4
4     2  4
...  .. ..
9995  2  2
9996  3  2
9997  1  6
9998  2  6
9999  5  2

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls[0] == die_rolls[1]

0       False
1       False
2       False
3       False
4       False
        ...  
9995     True
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [4]:
# aggregate to get probability
(die_rolls[0] == die_rolls[1]).mean()

0.1586

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 1]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([4, 5, 6, ..., 3, 3, 3])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.218

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6399

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[0, 0],
       [0, 1],
       [1, 0],
       ...,
       [1, 0],
       [0, 0],
       [1, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([0, 1, 1, ..., 1, 0, 1])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0611

In [49]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.random.normal(3, 1.5, size=(10_000, 5)).round()
poptarts

array([[ 2.,  4.,  1.,  4.,  3.],
       [ 4.,  3.,  0.,  3.,  3.],
       [ 4.,  2.,  2.,  2.,  3.],
       ...,
       [-1.,  0.,  3.,  2.,  1.],
       [ 1.,  3.,  1.,  2.,  0.],
       [ 0.,  3.,  2.,  6.,  5.]])

In [51]:
np.where(poptarts < 0, 0, poptarts)

array([[2., 4., 1., 4., 3.],
       [4., 3., 0., 3., 3.],
       [4., 2., 2., 2., 3.],
       ...,
       [0., 0., 3., 2., 1.],
       [1., 3., 1., 2., 0.],
       [0., 3., 2., 6., 5.]])

In [52]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([14., 13., 13., ...,  5.,  7., 16.])

In [53]:
# aggregate to get probability
(sum_of_poptarts <= 16).mean()

0.6679

In [15]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))
# aggregate rows-wise
comparison = (women > men) == True
# aggregate for probability
comparison.mean()

0.2143

In [54]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [56]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([49, 50, 50, ..., 50, 50, 50])

In [57]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8163

In [61]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [62]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([ 98, 100,  99, ...,  99,  99, 100])

In [63]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.6694

In [64]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [65]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([149, 150, 149, ..., 150, 149, 150])

In [66]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4541

In [67]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [68]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([448, 449, 448, ..., 450, 448, 450])

In [69]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1558