In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     3  1
1     2  1
2     1  3
3     3  2
4     2  2
...  .. ..
9995  1  3
9996  1  1
9997  1  2
9998  3  6
9999  5  3

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls["doubles"] = die_rolls[0] == die_rolls[1]
die_rolls

0  1  doubles
0     3  1    False
1     2  1    False
2     1  3    False
3     3  2    False
4     2  2     True
...  .. ..      ...
9995  1  3    False
9996  1  1     True
9997  1  2    False
9998  3  6    False
9999  5  3    False

[10000 rows x 3 columns]

In [4]:
# aggregate to get probability
(die_rolls.doubles).mean()

0.1718

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([2, 4, 4, ..., 5, 3, 2])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.2152

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6429

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[1, 0],
       [0, 1],
       [1, 0],
       ...,
       [1, 0],
       [1, 0],
       [0, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([1, 1, 1, ..., 1, 1, 0])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0637

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.round(np.random.normal(3, 1.5, size=(10_000, 5)))
poptarts

array([[ 6.,  5., -1.,  3.,  5.],
       [ 6.,  3.,  3.,  3.,  6.],
       [ 0.,  2.,  6.,  3.,  3.],
       ...,
       [ 1.,  3.,  2.,  6., -1.],
       [ 1.,  4.,  4.,  5.,  3.],
       [ 3.,  4.,  4.,  3.,  2.]])

In [13]:
poptarts.std()

1.5269839506687686

In [14]:
poptarts.mean()

3.00012

In [15]:
np.where(poptarts < 0, 0, poptarts)

array([[6., 5., 0., 3., 5.],
       [6., 3., 3., 3., 6.],
       [0., 2., 6., 3., 3.],
       ...,
       [1., 3., 2., 6., 0.],
       [1., 4., 4., 5., 3.],
       [3., 4., 4., 3., 2.]])

In [16]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([18., 21., 14., ..., 11., 17., 16.])

In [17]:
# aggregate to get probability
(sum_of_poptarts < 17).mean()

0.6702

In [18]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))

In [19]:
# aggregate rows-wise
comparison = (women > men)
comparison

array([False, False, False, ..., False, False, False])

In [20]:
# aggregate for probability
comparison.mean()

0.2183

In [21]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [22]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([50, 50, 50, ..., 49, 50, 50])

In [23]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8237

In [24]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [25]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([100,  99, 100, ..., 100, 100, 100])

In [26]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.6718

In [27]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [28]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([149, 149, 150, ..., 150, 150, 150])

In [29]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4541

In [30]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [31]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([445, 447, 449, ..., 449, 449, 449])

In [32]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1614

In [33]:
# 7. There's a 70% chance on any given day that there will be at
# least one food truck at Travis Park.
# However, you haven't seen a food truck there in 3 days.
# How unlikely is this?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_3_days = np.random.choice([0, 1], size=(10_000,3), p=[.3, .7])
food_truck_appearances_3_days

array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 0]])

In [34]:
# aggregate row-wise
sum_of_appearances_3_days = food_truck_appearances_3_days.sum(axis=1)
sum_of_appearances_3_days

array([1, 2, 3, ..., 3, 2, 2])

In [35]:
# aggregate for probability
(sum_of_appearances_3_days == 0).mean()

0.0286

In [36]:
# How likely is it that a food truck will show up sometime this week?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_week = np.random.choice([0, 1], size=(10_000,7), p=[.3, .7])
food_truck_appearances_week

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 1],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 1]])

In [37]:
# aggregate row-wise
sum_of_appearances_week = food_truck_appearances_week.sum(axis=1)
sum_of_appearances_week

array([2, 6, 6, ..., 4, 5, 5])

In [38]:
# aggregate for probability
(sum_of_appearances_week > 0).mean()

0.9995

In [39]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday?

# represent data
# create matrix
birthdays_23 = np.random.choice(range(1, 366), size=(10_000, 23))
birthdays_23 = pd.DataFrame(birthdays_23)
birthdays_23

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     267  176  241  117   61  132  108  134  223  110  ...   18   92  155   
1      14  335  137  266  362  221  195  151  310  272  ...   62  270  193   
2     252   55   92  194  135  117  219  286   99  133  ...  197  161   92   
3      81  329   73   50  326  137  213  356  108   15  ...   29  282   29   
4      40  196   83  144  336  356   74   55  191  272  ...  175  287   92   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  135   38  269  222  246  176  134  240  229    4  ...  177  244   88   
9996  186   14  196   31   63  328  245   71  357   46  ...  131   17  143   
9997  296  113   23   21   86   10  230  213  224  204  ...   20  104   73   
9998  310  326  102   47  242  163  233  318  229  344  ...   55  310  241   
9999  346   14   96  319  338  107  176  112  325  158  ...   49   91  202   

       16   17   18   19   20   21   22  
0     133  239   91  336  173  253   30  
1     330  199  227  363  243  202  319  
2      68   75  226   14  268  151  105  
3     168  256  259  260  169   29  246  
4     305  321   57  226  148   65  175  
...   ...  ...  ...  ...  ...  ...  ...  
9995  301  133  319   39  343  309  300  
9996  190  339  157  274  297  280  203  
9997  355  230  247  204   90  290  157  
9998  223  158  281  128  350  108  130  
9999   88  346  311  187  134  102  121  

[10000 rows x 23 columns]

In [40]:
# aggregate row-wise
birthdays_23["count_of_unique_birthdays"] = birthdays_23.nunique(axis=1)
birthdays_23

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0     267  176  241  117   61  132  108  134  223  110  ...   92  155  133   
1      14  335  137  266  362  221  195  151  310  272  ...  270  193  330   
2     252   55   92  194  135  117  219  286   99  133  ...  161   92   68   
3      81  329   73   50  326  137  213  356  108   15  ...  282   29  168   
4      40  196   83  144  336  356   74   55  191  272  ...  287   92  305   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  135   38  269  222  246  176  134  240  229    4  ...  244   88  301   
9996  186   14  196   31   63  328  245   71  357   46  ...   17  143  190   
9997  296  113   23   21   86   10  230  213  224  204  ...  104   73  355   
9998  310  326  102   47  242  163  233  318  229  344  ...  310  241  223   
9999  346   14   96  319  338  107  176  112  325  158  ...   91  202   88   

       17   18   19   20   21   22  count_of_unique_birthdays  
0     239   91  336  173  253   30                         23  
1     199  227  363  243  202  319                         23  
2      75  226   14  268  151  105                         22  
3     256  259  260  169   29  246                         21  
4     321   57  226  148   65  175                         21  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  133  319   39  343  309  300                         23  
9996  339  157  274  297  280  203                         23  
9997  230  247  204   90  290  157                         21  
9998  158  281  128  350  108  130                         22  
9999  346  311  187  134  102  121                         22  

[10000 rows x 24 columns]

In [41]:
# aggregate for probability
(birthdays_23["count_of_unique_birthdays"] < 23).mean()

0.5126

In [42]:
# What if it's 20 people?

# represent data
# create matrix
birthdays_20 = np.random.choice(range(1, 366), size=(10_000, 20))
birthdays_20 = pd.DataFrame(birthdays_20)
birthdays_20

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     185  318  361   68   30  202  292   87  250   66  211  170  130  158   
1     179  133  103  260  349  324  322  344   76  269  295   44   92  145   
2      53  280  106  121   25  182  290   38  185  358  158  175   75  126   
3     164  291   89  109  303  362   91  159  176  133  256  105    1  364   
4     365  226  265  163  224   81  126  261  348   59  178  258  191  300   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  350  273  256  352  351   70  342  257  193  319   57  262    2  111   
9996  110   30  231  107  338   66  181  319   68  108  130  248  199  220   
9997  103  358  350   75  174  162  323  114  236  320  340   28  221  169   
9998   46   12  241   18  362  212  211  364  243  285  153  296  148  236   
9999  250  312   96  358  345  351  187   42  350  298  354    7  184  351   

       14   15   16   17   18   19  
0       7  247   57  363  324  273  
1     346  315    2  159   56   97  
2      50  242  333  339  177  214  
3     205  324   65  164  195  182  
4     212  300  117  350  327   57  
...   ...  ...  ...  ...  ...  ...  
9995  231   97    4   78  151  322  
9996  227  278   63  187   59   19  
9997  148  160  238  345   29  280  
9998  251  164  272  242  264   85  
9999  247  133  153   83  148   22  

[10000 rows x 20 columns]

In [43]:
# aggregate row-wise
birthdays_20["count_of_unique_birthdays"] = birthdays_20.nunique(axis=1)
birthdays_20

0    1    2    3    4    5    6    7    8    9  ...   11   12   13  \
0     185  318  361   68   30  202  292   87  250   66  ...  170  130  158   
1     179  133  103  260  349  324  322  344   76  269  ...   44   92  145   
2      53  280  106  121   25  182  290   38  185  358  ...  175   75  126   
3     164  291   89  109  303  362   91  159  176  133  ...  105    1  364   
4     365  226  265  163  224   81  126  261  348   59  ...  258  191  300   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  350  273  256  352  351   70  342  257  193  319  ...  262    2  111   
9996  110   30  231  107  338   66  181  319   68  108  ...  248  199  220   
9997  103  358  350   75  174  162  323  114  236  320  ...   28  221  169   
9998   46   12  241   18  362  212  211  364  243  285  ...  296  148  236   
9999  250  312   96  358  345  351  187   42  350  298  ...    7  184  351   

       14   15   16   17   18   19  count_of_unique_birthdays  
0       7  247   57  363  324  273                         20  
1     346  315    2  159   56   97                         20  
2      50  242  333  339  177  214                         20  
3     205  324   65  164  195  182                         19  
4     212  300  117  350  327   57                         19  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  231   97    4   78  151  322                         20  
9996  227  278   63  187   59   19                         20  
9997  148  160  238  345   29  280                         20  
9998  251  164  272  242  264   85                         20  
9999  247  133  153   83  148   22                         19  

[10000 rows x 21 columns]

In [44]:
# aggregate for probability
(birthdays_20["count_of_unique_birthdays"] < 20).mean()

0.4165

In [45]:
# 40?

# represent data
# create matrix
birthdays_40 = np.random.choice(range(1, 366), size=(10_000, 40))
birthdays_40 = pd.DataFrame(birthdays_40)
birthdays_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0     283  235   82   47  100  164  297  183  338  365  ...  352  347   46   
1      64  272   84   99  285   54  221  161  364   61  ...   94  131  359   
2      48  223  120    1   59  222  348  255   34  229  ...   75  215  274   
3     167  139  163  267  102   21  243   78   44  173  ...  206   50  215   
4     270  362  332   90  115  231  274  238  234  344  ...    4  269  236   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  223   15  159  142  173    5   72  327  116  355  ...   51    5   59   
9996   95  263   87  355   66    4   13  264  243    9  ...  281   87   71   
9997  323  210  128  309  315  290  197   82  224  295  ...  198  348   18   
9998  188  289    5  265  338  218  232   27  217  124  ...   74   95  225   
9999  350  193    1  121  241  260  222  355   81  314  ...  288  287  273   

       33   34   35   36   37   38   39  
0      99  104  315    6  103  124  115  
1     146   79  266   97    2  352  114  
2     223   60  321   51    5  296  100  
3     302  134    5   52   55   54   29  
4      21  324   92  204  130  337  335  
...   ...  ...  ...  ...  ...  ...  ...  
9995  103  245   44  310  335  268   54  
9996  171   36  250  148  241  133  332  
9997  158   74  176   85  142  147   68  
9998  243  244   78  129  349  253   48  
9999  311  365   32  342   68  128  253  

[10000 rows x 40 columns]

In [46]:
# aggregate row-wise
birthdays_40["count_of_unique_birthdays"] = birthdays_40.nunique(axis=1)
birthdays_40

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0     283  235   82   47  100  164  297  183  338  365  ...  347   46   99   
1      64  272   84   99  285   54  221  161  364   61  ...  131  359  146   
2      48  223  120    1   59  222  348  255   34  229  ...  215  274  223   
3     167  139  163  267  102   21  243   78   44  173  ...   50  215  302   
4     270  362  332   90  115  231  274  238  234  344  ...  269  236   21   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  223   15  159  142  173    5   72  327  116  355  ...    5   59  103   
9996   95  263   87  355   66    4   13  264  243    9  ...   87   71  171   
9997  323  210  128  309  315  290  197   82  224  295  ...  348   18  158   
9998  188  289    5  265  338  218  232   27  217  124  ...   95  225  243   
9999  350  193    1  121  241  260  222  355   81  314  ...  287  273  311   

       34   35   36   37   38   39  count_of_unique_birthdays  
0     104  315    6  103  124  115                         38  
1      79  266   97    2  352  114                         40  
2      60  321   51    5  296  100                         38  
3     134    5   52   55   54   29                         40  
4     324   92  204  130  337  335                         40  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  245   44  310  335  268   54                         37  
9996   36  250  148  241  133  332                         37  
9997   74  176   85  142  147   68                         39  
9998  244   78  129  349  253   48                         40  
9999  365   32  342   68  128  253                         40  

[10000 rows x 41 columns]

In [47]:
# aggregate for probability
(birthdays_40["count_of_unique_birthdays"] < 40).mean()

0.8948