In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     4  5
1     2  5
2     3  5
3     1  2
4     6  4
...  .. ..
9995  3  4
9996  1  3
9997  5  2
9998  2  6
9999  4  3

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls[0] == die_rolls[1]

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [4]:
# aggregate to get probability
(die_rolls[0] == die_rolls[1]).mean()

0.1655

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[0, 1, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 0, 0]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([4, 3, 3, ..., 2, 5, 3])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.2205

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6396

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [1, 1],
       [0, 1],
       [0, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([2, 0, 0, ..., 2, 1, 0])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0584

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.random.normal(3, 1.5, size=(10_000, 5)).round()
poptarts

array([[4., 2., 4., 2., 4.],
       [4., 6., 2., 1., 4.],
       [1., 3., 2., 2., 1.],
       ...,
       [3., 1., 3., 3., 1.],
       [1., 2., 4., 2., 2.],
       [2., 3., 0., 4., 3.]])

In [13]:
np.where(poptarts < 0, 0, poptarts)

array([[4., 2., 4., 2., 4.],
       [4., 6., 2., 1., 4.],
       [1., 3., 2., 2., 1.],
       ...,
       [3., 1., 3., 3., 1.],
       [1., 2., 4., 2., 2.],
       [2., 3., 0., 4., 3.]])

In [14]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([16., 17.,  9., ..., 11., 11., 12.])

In [15]:
# aggregate to get probability
(sum_of_poptarts <= 16).mean()

0.6739

In [16]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))
# aggregate rows-wise
comparison = (women > men) == True
# aggregate for probability
comparison.mean()

0.217

In [17]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [18]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([50, 50, 50, ..., 50, 50, 50])

In [19]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8178

In [20]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [21]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([100, 100, 100, ...,  99, 100, 100])

In [22]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.6717

In [23]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [24]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([150, 150, 148, ..., 150, 150, 149])

In [25]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4528

In [26]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [27]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([449, 448, 447, ..., 448, 450, 448])

In [28]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1622

In [29]:
# 7. There's a 70% chance on any given day that there will be at
# least one food truck at Travis Park.
# However, you haven't seen a food truck there in 3 days.
# How unlikely is this?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_3_days = np.random.choice([0, 1], size=(10_000,3), p=[.3, .7])
food_truck_appearances_3_days

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1],
       ...,
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [30]:
# aggregate row-wise
sum_of_appearances_3_days = food_truck_appearances_3_days.sum(axis=1)
sum_of_appearances_3_days

array([2, 2, 2, ..., 1, 2, 3])

In [31]:
# aggregate for probability
(sum_of_appearances_3_days == 0).mean()

0.0275

In [32]:
# How likely is it that a food truck will show up sometime this week?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_week = np.random.choice([0, 1], size=(10_000,7), p=[.3, .7])
food_truck_appearances_week

array([[0, 0, 1, ..., 1, 1, 1],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 0, 0]])

In [33]:
# aggregate row-wise
sum_of_appearances_week = food_truck_appearances_week.sum(axis=1)
sum_of_appearances_week

array([5, 5, 5, ..., 6, 5, 4])

In [34]:
# aggregate for probability
(sum_of_appearances_week > 0).mean()

0.9999

In [35]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday?

# represent data
# create matrix
birthdays_23 = np.random.choice(range(1, 366), size=(10_000, 23))
birthdays_23 = pd.DataFrame(birthdays_23)
birthdays_23

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     201  245  108  205  341  280  300   11  117   11  ...  257  349  301   
1     330  125  100  337  247  144  257  322  343  326  ...  125  139   83   
2     308   54  156  141   76  332   81  227  119   92  ...   99   35  232   
3     270  144   49  273  234  173   72  213   22  143  ...   51  146   76   
4     136  282  320   13  154  112  207  298  184  208  ...   23  264  147   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   75  135   52  174  301  279  213  265  200  258  ...  209  258  228   
9996   73   14  282  331  104   22   69    6  327  289  ...  157  131  254   
9997  135  211  162   34  234  207  349   89  348  269  ...  259  124  243   
9998  295  297  180  353   29  175  124  105  195  225  ...  145  319  192   
9999   83  303   12  241  363  147  281   19  188   96  ...  349  267  194   

       16   17   18   19   20   21   22  
0     131  157  216   63   89   23   29  
1     208   94  277  220   19  321  227  
2     260  320  100  279   94   48   31  
3     318   81  298  359   84   58  155  
4     364   27  276  154  248  191  315  
...   ...  ...  ...  ...  ...  ...  ...  
9995  246  281  249   97   30  244  204  
9996  108  186  191  210   88  232   75  
9997  216  203  322  209  322  328  107  
9998  110   95  265  221  129  111  169  
9999   67  218  351  273  238  171  333  

[10000 rows x 23 columns]

In [36]:
# aggregate row-wise
birthdays_23["count_of_unique_birthdays"] = birthdays_23.nunique(axis=1)
birthdays_23

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0     201  245  108  205  341  280  300   11  117   11  ...  349  301  131   
1     330  125  100  337  247  144  257  322  343  326  ...  139   83  208   
2     308   54  156  141   76  332   81  227  119   92  ...   35  232  260   
3     270  144   49  273  234  173   72  213   22  143  ...  146   76  318   
4     136  282  320   13  154  112  207  298  184  208  ...  264  147  364   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   75  135   52  174  301  279  213  265  200  258  ...  258  228  246   
9996   73   14  282  331  104   22   69    6  327  289  ...  131  254  108   
9997  135  211  162   34  234  207  349   89  348  269  ...  124  243  216   
9998  295  297  180  353   29  175  124  105  195  225  ...  319  192  110   
9999   83  303   12  241  363  147  281   19  188   96  ...  267  194   67   

       17   18   19   20   21   22  count_of_unique_birthdays  
0     157  216   63   89   23   29                         22  
1      94  277  220   19  321  227                         21  
2     320  100  279   94   48   31                         23  
3      81  298  359   84   58  155                         23  
4      27  276  154  248  191  315                         22  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  281  249   97   30  244  204                         22  
9996  186  191  210   88  232   75                         23  
9997  203  322  209  322  328  107                         21  
9998   95  265  221  129  111  169                         23  
9999  218  351  273  238  171  333                         23  

[10000 rows x 24 columns]

In [48]:
# aggregate for probability
(birthdays_23["count_of_unique_birthdays"] < 23).mean()

0.5074

In [44]:
# What if it's 20 people?

# represent data
# create matrix
birthdays_20 = np.random.choice(range(1, 366), size=(10_000, 20))
birthdays_20 = pd.DataFrame(birthdays_20)
birthdays_20

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     349  322   38  251  308  325  235  186  204  306   11  339   72   25   
1      56  155    8  350   89   57   53  125  195  218   82  213  264   86   
2     164  320  162  217   29  334  317   84   28  259  266  256  250    8   
3     307  161  287  322  265  171  299  158   48   89  274  258  227   69   
4     322  151  141  154   46   67  271  338   80  282   86  148   89  252   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   49   81   99  215  269  191  151   30  310  120  107   87  165  105   
9996  109   92  125  305  146  155  221  214  200   34   48  316  171  175   
9997  277  314  121  313  172  322  278  282   60  266   75  157  287  338   
9998  345   20  123  219  148   18  154  113  222  160  118  353   21  190   
9999  237  225   25   28  133   57  116   46  251   22  181  110   77   51   

       14   15   16   17   18   19  
0      38   44    4  210  302  142  
1      19  300  137   70  159   15  
2       1  112  122  274   64   26  
3      39  312  314  289  164  344  
4      55   90   38  304  151  189  
...   ...  ...  ...  ...  ...  ...  
9995  324  283  132  256   31  177  
9996   89   94  230  257  266  286  
9997  101   31   81   22  126   87  
9998  187  297  146    6  218   31  
9999  102  238  292  218  347  185  

[10000 rows x 20 columns]

In [45]:
# aggregate row-wise
birthdays_20["count_of_unique_birthdays"] = birthdays_20.nunique(axis=1)
birthdays_20

0    1    2    3    4    5    6    7    8    9  ...   11   12   13  \
0     349  322   38  251  308  325  235  186  204  306  ...  339   72   25   
1      56  155    8  350   89   57   53  125  195  218  ...  213  264   86   
2     164  320  162  217   29  334  317   84   28  259  ...  256  250    8   
3     307  161  287  322  265  171  299  158   48   89  ...  258  227   69   
4     322  151  141  154   46   67  271  338   80  282  ...  148   89  252   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   49   81   99  215  269  191  151   30  310  120  ...   87  165  105   
9996  109   92  125  305  146  155  221  214  200   34  ...  316  171  175   
9997  277  314  121  313  172  322  278  282   60  266  ...  157  287  338   
9998  345   20  123  219  148   18  154  113  222  160  ...  353   21  190   
9999  237  225   25   28  133   57  116   46  251   22  ...  110   77   51   

       14   15   16   17   18   19  count_of_unique_birthdays  
0      38   44    4  210  302  142                         19  
1      19  300  137   70  159   15                         20  
2       1  112  122  274   64   26                         20  
3      39  312  314  289  164  344                         20  
4      55   90   38  304  151  189                         19  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  324  283  132  256   31  177                         20  
9996   89   94  230  257  266  286                         20  
9997  101   31   81   22  126   87                         20  
9998  187  297  146    6  218   31                         20  
9999  102  238  292  218  347  185                         20  

[10000 rows x 21 columns]

In [49]:
# aggregate for probability
(birthdays_20["count_of_unique_birthdays"] < 20).mean()

0.4098

In [51]:
# 40?

# represent data
# create matrix
birthdays_40 = np.random.choice(range(1, 366), size=(10_000, 40))
birthdays_40 = pd.DataFrame(birthdays_40)
birthdays_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0       7   88   28  112  343  210   76  299   86  190  ...  103  164  284   
1     351  224   10   54  214  330  205   70  365  266  ...  178  295  304   
2     153  261  231  162  298  167   32  204  276  290  ...  261  185  305   
3     162   34  332  246  359  226  172  237   77  100  ...   76  326  171   
4      95  257   96  161  191  332  127   98  355  354  ...  266  230  200   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   40  149  275  346    9  316  340  132  315  100  ...   58  180  227   
9996  216  173  204  315   47  309  188  118   66  277  ...  108  289  354   
9997  153  211  301  227  267  336   24  184  226   53  ...   20    6  178   
9998  225  109  360  106  172  123  150   33   79  282  ...   35  105   59   
9999  277   66  301  335   18   16  157   78  138  329  ...  321    2   64   

       33   34   35   36   37   38   39  
0     266  249  181  146  297  292  335  
1     336   88  288  141  239  105  152  
2     231  243  282  289  128  192  308  
3     262    3  251  111  363   52  284  
4     130   76  275  189  362   73  305  
...   ...  ...  ...  ...  ...  ...  ...  
9995  189  362  336  309  320  158  242  
9996  194   45  266  353   68  138   48  
9997  155  286  236  211  173    3   29  
9998  100  167  180  179  311  308  314  
9999  182  237   32   14  188  136   99  

[10000 rows x 40 columns]

In [52]:
# aggregate row-wise
birthdays_40["count_of_unique_birthdays"] = birthdays_40.nunique(axis=1)
birthdays_40

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0       7   88   28  112  343  210   76  299   86  190  ...  164  284  266   
1     351  224   10   54  214  330  205   70  365  266  ...  295  304  336   
2     153  261  231  162  298  167   32  204  276  290  ...  185  305  231   
3     162   34  332  246  359  226  172  237   77  100  ...  326  171  262   
4      95  257   96  161  191  332  127   98  355  354  ...  230  200  130   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   40  149  275  346    9  316  340  132  315  100  ...  180  227  189   
9996  216  173  204  315   47  309  188  118   66  277  ...  289  354  194   
9997  153  211  301  227  267  336   24  184  226   53  ...    6  178  155   
9998  225  109  360  106  172  123  150   33   79  282  ...  105   59  100   
9999  277   66  301  335   18   16  157   78  138  329  ...    2   64  182   

       34   35   36   37   38   39  count_of_unique_birthdays  
0     249  181  146  297  292  335                         40  
1      88  288  141  239  105  152                         37  
2     243  282  289  128  192  308                         38  
3       3  251  111  363   52  284                         39  
4      76  275  189  362   73  305                         39  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  362  336  309  320  158  242                         39  
9996   45  266  353   68  138   48                         37  
9997  286  236  211  173    3   29                         37  
9998  167  180  179  311  308  314                         38  
9999  237   32   14  188  136   99                         39  

[10000 rows x 41 columns]

In [53]:
# aggregate for probability
(birthdays_40["count_of_unique_birthdays"] < 40).mean()

0.8948