In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     4  6
1     4  3
2     1  1
3     3  1
4     1  5
...  .. ..
9995  5  3
9996  4  2
9997  2  2
9998  1  5
9999  1  5

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls["doubles"] = die_rolls[0] == die_rolls[1]
die_rolls

0  1  doubles
0     4  6    False
1     4  3    False
2     1  1     True
3     3  1    False
4     1  5    False
...  .. ..      ...
9995  5  3    False
9996  4  2    False
9997  2  2     True
9998  1  5    False
9999  1  5    False

[10000 rows x 3 columns]

In [4]:
# aggregate to get probability
(die_rolls.doubles).mean()

0.171

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[1, 0, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 0, 1]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([5, 6, 7, ..., 4, 7, 3])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.2229

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6323

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[0, 0],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 0],
       [0, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([0, 1, 1, ..., 1, 0, 0])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0638

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.round(np.random.normal(3, 1.5, size=(10_000, 5)))
poptarts

array([[5., 3., 3., 0., 5.],
       [2., 3., 5., 3., 3.],
       [3., 3., 1., 3., 4.],
       ...,
       [1., 3., 4., 1., 1.],
       [6., 4., 2., 4., 2.],
       [3., 2., 4., 2., 3.]])

In [13]:
poptarts.std()

1.5274376682536017

In [14]:
poptarts.mean()

2.99264

In [15]:
np.where(poptarts < 0, 0, poptarts)

array([[5., 3., 3., 0., 5.],
       [2., 3., 5., 3., 3.],
       [3., 3., 1., 3., 4.],
       ...,
       [1., 3., 4., 1., 1.],
       [6., 4., 2., 4., 2.],
       [3., 2., 4., 2., 3.]])

In [16]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([16., 16., 14., ..., 10., 18., 14.])

In [17]:
# aggregate to get probability
(sum_of_poptarts < 17).mean()

0.6722

In [18]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))

In [19]:
# aggregate rows-wise
comparison = (women > men)
comparison

array([False, False, False, ...,  True, False,  True])

In [20]:
# aggregate for probability
comparison.mean()

0.2138

In [21]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [22]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([50, 50, 50, ..., 50, 50, 50])

In [23]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8157

In [24]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [25]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([ 99,  99, 100, ...,  99,  99,  99])

In [26]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.6814

In [27]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [28]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([149, 149, 150, ..., 150, 148, 149])

In [29]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4504

In [30]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [31]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([447, 449, 448, ..., 448, 450, 448])

In [32]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1645

In [33]:
# 7. There's a 70% chance on any given day that there will be at
# least one food truck at Travis Park.
# However, you haven't seen a food truck there in 3 days.
# How unlikely is this?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_3_days = np.random.choice([0, 1], size=(10_000,3), p=[.3, .7])
food_truck_appearances_3_days

array([[1, 0, 1],
       [1, 1, 1],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0]])

In [34]:
# aggregate row-wise
sum_of_appearances_3_days = food_truck_appearances_3_days.sum(axis=1)
sum_of_appearances_3_days

array([2, 3, 3, ..., 3, 3, 0])

In [35]:
# aggregate for probability
(sum_of_appearances_3_days == 0).mean()

0.0261

In [36]:
# How likely is it that a food truck will show up sometime this week?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_week = np.random.choice([0, 1], size=(10_000,7), p=[.3, .7])
food_truck_appearances_week

array([[1, 1, 0, ..., 0, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 0, 0]])

In [37]:
# aggregate row-wise
sum_of_appearances_week = food_truck_appearances_week.sum(axis=1)
sum_of_appearances_week

array([5, 6, 3, ..., 5, 5, 3])

In [38]:
# aggregate for probability
(sum_of_appearances_week > 0).mean()

0.9995

In [39]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday?

# represent data
# create matrix
birthdays_23 = np.random.choice(range(1, 366), size=(10_000, 23))
birthdays_23 = pd.DataFrame(birthdays_23)
birthdays_23

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     265  345  321  225  221    3  338  177  157   20  ...   84   53  308   
1     121  341  167  167  245  144  302  246  246    7  ...  113  191   35   
2     225  100  239  172    2  118    1  326   82  172  ...  242   11   78   
3      36  168  114  132  107  242  110  332   54  155  ...  330  260   40   
4     118  228  271  228   71   98  142   34  255  251  ...   81   42    4   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  137  120   83  147  345  270  198  345   87  107  ...  357  168  326   
9996  153   93   68  151  129  209   27  296  237  187  ...   91  288   54   
9997  230  119   13   34  112    3  304  309  330  356  ...  328  106  329   
9998  140   47   38  241  116  338   34  303    9  136  ...  128   13   51   
9999   18  294   53  253  339  331  282   86  304  293  ...   66   58   99   

       16   17   18   19   20   21   22  
0     117  261  349  336  274   72  208  
1     308  331  337  239  341    2  257  
2     303  226  248  225  304   29   46  
3     170  209  110  267   95  347  226  
4      18   49  101  119  136  182  350  
...   ...  ...  ...  ...  ...  ...  ...  
9995  269  355  239  355  181  280  291  
9996    7  269  347  292  114  238  133  
9997  122  127    9  359   81  346   81  
9998   51  311  267  359  238   72  262  
9999  102  313  148  350  189  188  351  

[10000 rows x 23 columns]

In [40]:
# aggregate row-wise
birthdays_23["count_of_unique_birthdays"] = birthdays_23.nunique(axis=1)
birthdays_23

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0     265  345  321  225  221    3  338  177  157   20  ...   53  308  117   
1     121  341  167  167  245  144  302  246  246    7  ...  191   35  308   
2     225  100  239  172    2  118    1  326   82  172  ...   11   78  303   
3      36  168  114  132  107  242  110  332   54  155  ...  260   40  170   
4     118  228  271  228   71   98  142   34  255  251  ...   42    4   18   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  137  120   83  147  345  270  198  345   87  107  ...  168  326  269   
9996  153   93   68  151  129  209   27  296  237  187  ...  288   54    7   
9997  230  119   13   34  112    3  304  309  330  356  ...  106  329  122   
9998  140   47   38  241  116  338   34  303    9  136  ...   13   51   51   
9999   18  294   53  253  339  331  282   86  304  293  ...   58   99  102   

       17   18   19   20   21   22  count_of_unique_birthdays  
0     261  349  336  274   72  208                         23  
1     331  337  239  341    2  257                         20  
2     226  248  225  304   29   46                         21  
3     209  110  267   95  347  226                         22  
4      49  101  119  136  182  350                         21  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  355  239  355  181  280  291                         21  
9996  269  347  292  114  238  133                         23  
9997  127    9  359   81  346   81                         22  
9998  311  267  359  238   72  262                         22  
9999  313  148  350  189  188  351                         23  

[10000 rows x 24 columns]

In [41]:
# aggregate for probability
(birthdays_23["count_of_unique_birthdays"] < 23).mean()

0.5038

In [42]:
# What if it's 20 people?

# represent data
# create matrix
birthdays_20 = np.random.choice(range(1, 366), size=(10_000, 20))
birthdays_20 = pd.DataFrame(birthdays_20)
birthdays_20

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     164  312  322  100   44   79  252    3  296  188  116  167  207  340   
1     222   76   33   73  364  173  334  215  108  351  155  288   41  256   
2       9   14  118  121  312  225  332  184  158  349    7  160  238  285   
3      64  105   66  142  335   70  298   15  296  179  300  108   60  182   
4     282  290  298  313  109  237   13  100   74  295  245   68  192  238   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  253  330  166   42  355   93  263   30  342   88   63  236  300  194   
9996  204  283  189   24  214  183  202  218  116  145   27  361  164  354   
9997  256  166   77   70  359  195   49    2  362  173   91  143  247  236   
9998   47    1   85  301  364   34  115  255   93  273    5    2  275  226   
9999  161  212  130  187  223  341   33  339  195  225   50  140    7  115   

       14   15   16   17   18   19  
0      47   70  138  243   25  255  
1     292  221  306  324  237    4  
2     274  255   78   86  293  248  
3      85  290  257  233  258   23  
4     279  145   78  318   66  302  
...   ...  ...  ...  ...  ...  ...  
9995   51  336  303  219  340  133  
9996  352   91  240  310  110  330  
9997  349    6   89  272  103  271  
9998   96   36  232  296  303  182  
9999  360   29  278  273   51  221  

[10000 rows x 20 columns]

In [43]:
# aggregate row-wise
birthdays_20["count_of_unique_birthdays"] = birthdays_20.nunique(axis=1)
birthdays_20

0    1    2    3    4    5    6    7    8    9  ...   11   12   13  \
0     164  312  322  100   44   79  252    3  296  188  ...  167  207  340   
1     222   76   33   73  364  173  334  215  108  351  ...  288   41  256   
2       9   14  118  121  312  225  332  184  158  349  ...  160  238  285   
3      64  105   66  142  335   70  298   15  296  179  ...  108   60  182   
4     282  290  298  313  109  237   13  100   74  295  ...   68  192  238   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  253  330  166   42  355   93  263   30  342   88  ...  236  300  194   
9996  204  283  189   24  214  183  202  218  116  145  ...  361  164  354   
9997  256  166   77   70  359  195   49    2  362  173  ...  143  247  236   
9998   47    1   85  301  364   34  115  255   93  273  ...    2  275  226   
9999  161  212  130  187  223  341   33  339  195  225  ...  140    7  115   

       14   15   16   17   18   19  count_of_unique_birthdays  
0      47   70  138  243   25  255                         20  
1     292  221  306  324  237    4                         20  
2     274  255   78   86  293  248                         20  
3      85  290  257  233  258   23                         20  
4     279  145   78  318   66  302                         20  
...   ...  ...  ...  ...  ...  ...                        ...  
9995   51  336  303  219  340  133                         20  
9996  352   91  240  310  110  330                         20  
9997  349    6   89  272  103  271                         20  
9998   96   36  232  296  303  182                         20  
9999  360   29  278  273   51  221                         20  

[10000 rows x 21 columns]

In [44]:
# aggregate for probability
(birthdays_20["count_of_unique_birthdays"] < 20).mean()

0.4155

In [45]:
# 40?

# represent data
# create matrix
birthdays_40 = np.random.choice(range(1, 366), size=(10_000, 40))
birthdays_40 = pd.DataFrame(birthdays_40)
birthdays_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0     100  200   59  133  215  200  340  312  283   40  ...   62  202  282   
1      97  123   27  242  333  216  299  131   54  302  ...  191  179  317   
2     101  229   98  131  158  356   88  343   79  279  ...  178  201  188   
3     218  167  168  157  365   40  268  137  256  332  ...  195  342  152   
4      48  101  254    6  262   76  286  351  165   20  ...   92   51  322   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  292  364  217  141  249  190  158  219  154  249  ...  271  190  258   
9996  274  188    9  139  344  204  156  177  224  314  ...  197  333  139   
9997  347  232  315  127  334   26   39  244  110   24  ...  334   82  174   
9998    4  208   81   15  317  252    1  191   66  304  ...   56   51  213   
9999  180   12  233  138  362   96  140  227  183  264  ...   93  203  110   

       33   34   35   36   37   38   39  
0      76   66   60   97   50  331   51  
1     104  194  164   17  282  164  128  
2      10   51  322  236  175  155  231  
3      58  228  146  280  147  322   38  
4     314  308  198   35  318   68   53  
...   ...  ...  ...  ...  ...  ...  ...  
9995  162   90   54   66  172  110  217  
9996   40   26  245  292  122   47  206  
9997  201  213   54  282  223  167  186  
9998   57    2  288  269  360  253  115  
9999  119  354  186  346   89   26   59  

[10000 rows x 40 columns]

In [46]:
# aggregate row-wise
birthdays_40["count_of_unique_birthdays"] = birthdays_40.nunique(axis=1)
birthdays_40

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0     100  200   59  133  215  200  340  312  283   40  ...  202  282   76   
1      97  123   27  242  333  216  299  131   54  302  ...  179  317  104   
2     101  229   98  131  158  356   88  343   79  279  ...  201  188   10   
3     218  167  168  157  365   40  268  137  256  332  ...  342  152   58   
4      48  101  254    6  262   76  286  351  165   20  ...   51  322  314   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  292  364  217  141  249  190  158  219  154  249  ...  190  258  162   
9996  274  188    9  139  344  204  156  177  224  314  ...  333  139   40   
9997  347  232  315  127  334   26   39  244  110   24  ...   82  174  201   
9998    4  208   81   15  317  252    1  191   66  304  ...   51  213   57   
9999  180   12  233  138  362   96  140  227  183  264  ...  203  110  119   

       34   35   36   37   38   39  count_of_unique_birthdays  
0      66   60   97   50  331   51                         38  
1     194  164   17  282  164  128                         37  
2      51  322  236  175  155  231                         40  
3     228  146  280  147  322   38                         40  
4     308  198   35  318   68   53                         39  
...   ...  ...  ...  ...  ...  ...                        ...  
9995   90   54   66  172  110  217                         35  
9996   26  245  292  122   47  206                         39  
9997  213   54  282  223  167  186                         38  
9998    2  288  269  360  253  115                         36  
9999  354  186  346   89   26   59                         38  

[10000 rows x 41 columns]

In [47]:
# aggregate for probability
(birthdays_40["count_of_unique_birthdays"] < 40).mean()

0.8849