In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     6  4
1     5  5
2     6  3
3     6  6
4     6  4
...  .. ..
9995  5  2
9996  2  4
9997  2  1
9998  2  4
9999  6  6

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls["doubles"] = die_rolls[0] == die_rolls[1]
die_rolls

0  1  doubles
0     6  4    False
1     5  5     True
2     6  3    False
3     6  6     True
4     6  4    False
...  .. ..      ...
9995  5  2    False
9996  2  4    False
9997  2  1    False
9998  2  4    False
9999  6  6     True

[10000 rows x 3 columns]

In [4]:
# aggregate to get probability
(die_rolls.doubles).mean()

0.1687

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[1, 1, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 0, 0]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([4, 2, 2, ..., 4, 5, 3])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.2222

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6358

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [1, 1],
       [1, 0],
       [0, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([0, 0, 0, ..., 2, 1, 0])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.063

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.round(np.random.normal(3, 1.5, size=(10_000, 5)))
poptarts

array([[4., 4., 1., 4., 4.],
       [4., 1., 5., 3., 3.],
       [4., 0., 1., 6., 3.],
       ...,
       [1., 3., 5., 3., 2.],
       [2., 3., 2., 6., 3.],
       [4., 5., 2., 2., 3.]])

In [13]:
poptarts.std()

1.5211697907860253

In [14]:
poptarts.mean()

2.99526

In [15]:
np.where(poptarts < 0, 0, poptarts)

array([[4., 4., 1., 4., 4.],
       [4., 1., 5., 3., 3.],
       [4., 0., 1., 6., 3.],
       ...,
       [1., 3., 5., 3., 2.],
       [2., 3., 2., 6., 3.],
       [4., 5., 2., 2., 3.]])

In [16]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([17., 16., 14., ..., 14., 16., 16.])

In [17]:
# aggregate to get probability
(sum_of_poptarts < 17).mean()

0.6725

In [18]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))

In [19]:
# aggregate rows-wise
comparison = (women > men)
comparison

array([False, False, False, ...,  True, False, False])

In [20]:
# aggregate for probability
comparison.mean()

0.2133

In [21]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [22]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([50, 50, 49, ..., 50, 50, 49])

In [23]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8218

In [24]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [25]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([ 99, 100, 100, ...,  98,  99,  99])

In [26]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.674

In [27]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [28]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([150, 149, 149, ..., 150, 149, 150])

In [29]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4501

In [30]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [31]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([449, 450, 449, ..., 447, 449, 450])

In [32]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1628

In [33]:
# 7. There's a 70% chance on any given day that there will be at
# least one food truck at Travis Park.
# However, you haven't seen a food truck there in 3 days.
# How unlikely is this?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_3_days = np.random.choice([0, 1], size=(10_000,3), p=[.3, .7])
food_truck_appearances_3_days

array([[0, 1, 0],
       [1, 1, 1],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 1]])

In [34]:
# aggregate row-wise
sum_of_appearances_3_days = food_truck_appearances_3_days.sum(axis=1)
sum_of_appearances_3_days

array([1, 3, 0, ..., 0, 2, 2])

In [35]:
# aggregate for probability
(sum_of_appearances_3_days == 0).mean()

0.0256

In [36]:
# How likely is it that a food truck will show up sometime this week?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_week = np.random.choice([0, 1], size=(10_000,7), p=[.3, .7])
food_truck_appearances_week

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 0, 0]])

In [37]:
# aggregate row-wise
sum_of_appearances_week = food_truck_appearances_week.sum(axis=1)
sum_of_appearances_week

array([2, 5, 4, ..., 6, 3, 3])

In [38]:
# aggregate for probability
(sum_of_appearances_week > 0).mean()

1.0

In [39]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday?

# represent data
# create matrix
birthdays_23 = np.random.choice(range(1, 366), size=(10_000, 23))
birthdays_23 = pd.DataFrame(birthdays_23)
birthdays_23

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     237  124  166  261  334  205  207  180  318  242  ...  146  242   68   
1     123  187  286   61   45   52  154  347  267  284  ...  184   43  101   
2     263  223  233  184  222  274  362  288  358  202  ...   67  303   72   
3     120  184  263  184  136   29  156   73  177  109  ...  185   34  283   
4     227   30  174  210   60  318  148  197  307   53  ...  121  159   31   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  215  315  284  193  301  353   77  337  127  331  ...   69  340  210   
9996  282  336   94   30   42  242  224  295  199  335  ...  216  214  207   
9997  339  328   15  127  362  198   64  195  273  266  ...  292  245  361   
9998  308   50   72    8  136   38  220  203  255   42  ...   73  272  164   
9999  275  105  351  350  300  135  230  289   26  126  ...  255  227  250   

       16   17   18   19   20   21   22  
0      39  359  325  164  211   20  264  
1     204   81   78   26  301  247  243  
2     311  121  259  309  137  141   87  
3      30  152  279  314  318   65  144  
4     330   70  272   43  165  251  184  
...   ...  ...  ...  ...  ...  ...  ...  
9995  173  173  263   56  229   65  309  
9996  228   94  326   91   32  161  144  
9997   26  132  199  242   59   69  151  
9998   82  149  332  254  199   64  364  
9999  127   89  162  236  340   60  334  

[10000 rows x 23 columns]

In [40]:
# aggregate row-wise
birthdays_23["count_of_unique_birthdays"] = birthdays_23.nunique(axis=1)
birthdays_23

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0     237  124  166  261  334  205  207  180  318  242  ...  242   68   39   
1     123  187  286   61   45   52  154  347  267  284  ...   43  101  204   
2     263  223  233  184  222  274  362  288  358  202  ...  303   72  311   
3     120  184  263  184  136   29  156   73  177  109  ...   34  283   30   
4     227   30  174  210   60  318  148  197  307   53  ...  159   31  330   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  215  315  284  193  301  353   77  337  127  331  ...  340  210  173   
9996  282  336   94   30   42  242  224  295  199  335  ...  214  207  228   
9997  339  328   15  127  362  198   64  195  273  266  ...  245  361   26   
9998  308   50   72    8  136   38  220  203  255   42  ...  272  164   82   
9999  275  105  351  350  300  135  230  289   26  126  ...  227  250  127   

       17   18   19   20   21   22  count_of_unique_birthdays  
0     359  325  164  211   20  264                         22  
1      81   78   26  301  247  243                         22  
2     121  259  309  137  141   87                         23  
3     152  279  314  318   65  144                         21  
4      70  272   43  165  251  184                         23  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  173  263   56  229   65  309                         22  
9996   94  326   91   32  161  144                         22  
9997  132  199  242   59   69  151                         23  
9998  149  332  254  199   64  364                         23  
9999   89  162  236  340   60  334                         23  

[10000 rows x 24 columns]

In [41]:
# aggregate for probability
(birthdays_23["count_of_unique_birthdays"] < 23).mean()

0.5111

In [42]:
# What if it's 20 people?

# represent data
# create matrix
birthdays_20 = np.random.choice(range(1, 366), size=(10_000, 20))
birthdays_20 = pd.DataFrame(birthdays_20)
birthdays_20

0    1    2    3    4    5    6    7    8    9   10   11   12   13  \
0     111  195   37   30   70  249  288  262  119  265  140  132  310  248   
1     206  355  335  179  233  230   97   53   95  262  131  257  237  343   
2     157  171  148  335  134  164  154   88   41  209  244  297   90  259   
3      38  214  132  178  308  335  349   55  196  359  260  280  232  255   
4     295   15  143  174  235  323  177  306   97   86  328  308  186  259   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  198  185   68   68  202   50  300  158  198  147   60  246   65  107   
9996  205  179   75  131  285   77   39  302   98  239   18  174   16  183   
9997   86  111  295  260   64  342  160  158  233   65  355  231  324  227   
9998  134  114  336   59   39  235    3   35  250  213   48   70   43  286   
9999  114   75   60  363   92  252  355  247  141  334  240    4   25  269   

       14   15   16   17   18   19  
0     342  123  110   83   73   50  
1     208  169  308   91   52  362  
2      92   27   71   19  228   73  
3      44  191  229  158   32  217  
4     226  156  209   52  138  248  
...   ...  ...  ...  ...  ...  ...  
9995   50  290  240  229  220  117  
9996  281  206  115  292  321  204  
9997  278  126  342   56  358  163  
9998   75  263   63  154   98  210  
9999   78  271  237   29  312  139  

[10000 rows x 20 columns]

In [43]:
# aggregate row-wise
birthdays_20["count_of_unique_birthdays"] = birthdays_20.nunique(axis=1)
birthdays_20

0    1    2    3    4    5    6    7    8    9  ...   11   12   13  \
0     111  195   37   30   70  249  288  262  119  265  ...  132  310  248   
1     206  355  335  179  233  230   97   53   95  262  ...  257  237  343   
2     157  171  148  335  134  164  154   88   41  209  ...  297   90  259   
3      38  214  132  178  308  335  349   55  196  359  ...  280  232  255   
4     295   15  143  174  235  323  177  306   97   86  ...  308  186  259   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  198  185   68   68  202   50  300  158  198  147  ...  246   65  107   
9996  205  179   75  131  285   77   39  302   98  239  ...  174   16  183   
9997   86  111  295  260   64  342  160  158  233   65  ...  231  324  227   
9998  134  114  336   59   39  235    3   35  250  213  ...   70   43  286   
9999  114   75   60  363   92  252  355  247  141  334  ...    4   25  269   

       14   15   16   17   18   19  count_of_unique_birthdays  
0     342  123  110   83   73   50                         20  
1     208  169  308   91   52  362                         20  
2      92   27   71   19  228   73                         20  
3      44  191  229  158   32  217                         20  
4     226  156  209   52  138  248                         20  
...   ...  ...  ...  ...  ...  ...                        ...  
9995   50  290  240  229  220  117                         17  
9996  281  206  115  292  321  204                         20  
9997  278  126  342   56  358  163                         19  
9998   75  263   63  154   98  210                         20  
9999   78  271  237   29  312  139                         20  

[10000 rows x 21 columns]

In [44]:
# aggregate for probability
(birthdays_20["count_of_unique_birthdays"] < 20).mean()

0.4187

In [45]:
# 40?

# represent data
# create matrix
birthdays_40 = np.random.choice(range(1, 366), size=(10_000, 40))
birthdays_40 = pd.DataFrame(birthdays_40)
birthdays_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0      95  217  211    4   99  271  358  226   27  302  ...  104    6    1   
1     270  276  331  201   81  149   10   92  133  121  ...  214  356  334   
2      53   13  211   54   39  293  318  157   59  209  ...  320  190  176   
3     336   96  159  300   17  324   42   18  102  312  ...  333  196   53   
4      22  131  310   92   54  310   62    4   44   91  ...   14   46   38   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  294  200  343  130   73  102   35  250  138  356  ...   46  281   86   
9996  146  287   17  144  263   74   50   97  146  243  ...  230  137   66   
9997   96   54  220  200  223  161  313    3  354  151  ...  158   85   97   
9998  210   12  356   37   14  321   83  180  116  138  ...  105  186  122   
9999  337  303  235   13  186  295   16  327   63  342  ...   81  341  249   

       33   34   35   36   37   38   39  
0      24  304  213   16  219  323  160  
1     306  340  104  285  354   64  209  
2     289  267  257  174   37  143  335  
3      25  327  128  227   73  281   10  
4     119  273   93   96    6  296  249  
...   ...  ...  ...  ...  ...  ...  ...  
9995   10  324    7  185  308    3   59  
9996   84  217    2  208  114  170  172  
9997  220   37  210  229  211  228  281  
9998  164  191  171  174  148  238  232  
9999   75   52  151  232   52  218  121  

[10000 rows x 40 columns]

In [46]:
# aggregate row-wise
birthdays_40["count_of_unique_birthdays"] = birthdays_40.nunique(axis=1)
birthdays_40

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0      95  217  211    4   99  271  358  226   27  302  ...    6    1   24   
1     270  276  331  201   81  149   10   92  133  121  ...  356  334  306   
2      53   13  211   54   39  293  318  157   59  209  ...  190  176  289   
3     336   96  159  300   17  324   42   18  102  312  ...  196   53   25   
4      22  131  310   92   54  310   62    4   44   91  ...   46   38  119   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  294  200  343  130   73  102   35  250  138  356  ...  281   86   10   
9996  146  287   17  144  263   74   50   97  146  243  ...  137   66   84   
9997   96   54  220  200  223  161  313    3  354  151  ...   85   97  220   
9998  210   12  356   37   14  321   83  180  116  138  ...  186  122  164   
9999  337  303  235   13  186  295   16  327   63  342  ...  341  249   75   

       34   35   36   37   38   39  count_of_unique_birthdays  
0     304  213   16  219  323  160                         40  
1     340  104  285  354   64  209                         38  
2     267  257  174   37  143  335                         39  
3     327  128  227   73  281   10                         38  
4     273   93   96    6  296  249                         38  
...   ...  ...  ...  ...  ...  ...                        ...  
9995  324    7  185  308    3   59                         39  
9996  217    2  208  114  170  172                         38  
9997   37  210  229  211  228  281                         39  
9998  191  171  174  148  238  232                         37  
9999   52  151  232   52  218  121                         37  

[10000 rows x 41 columns]

In [47]:
# aggregate for probability
(birthdays_40["count_of_unique_birthdays"] < 40).mean()

0.8939