In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     3  2
1     2  6
2     6  3
3     2  4
4     2  2
...  .. ..
9995  6  4
9996  3  2
9997  1  6
9998  1  1
9999  2  5

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls[0] == die_rolls[1]

0       False
1       False
2       False
3       False
4        True
        ...  
9995    False
9996    False
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [4]:
# aggregate to get probability
(die_rolls[0] == die_rolls[1]).mean()

0.1682

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[0, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 0]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([4, 5, 5, ..., 6, 4, 6])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.2205

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6343

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[0, 1],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [0, 0],
       [0, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([1, 1, 1, ..., 1, 0, 0])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0641

In [12]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = np.random.normal(3, 1.5, size=(10_000, 5)).round()
poptarts

array([[2., 3., 3., 5., 3.],
       [2., 2., 2., 3., 4.],
       [3., 3., 6., 4., 3.],
       ...,
       [2., 3., 5., 3., 4.],
       [2., 3., 2., 4., 1.],
       [2., 4., 3., 2., 2.]])

In [13]:
np.where(poptarts < 0, 0, poptarts)

array([[2., 3., 3., 5., 3.],
       [2., 2., 2., 3., 4.],
       [3., 3., 6., 4., 3.],
       ...,
       [2., 3., 5., 3., 4.],
       [2., 3., 2., 4., 1.],
       [2., 4., 3., 2., 2.]])

In [14]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([16., 13., 19., ..., 17., 12., 13.])

In [15]:
# aggregate to get probability
(sum_of_poptarts <= 16).mean()

0.6701

In [16]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))
# aggregate rows-wise
comparison = (women > men) == True
# aggregate for probability
comparison.mean()

0.2114

In [17]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_50 = np.random.choice([0, 1], size=(10_000, 50), p=[1/250, 249/250])
conda_downloads_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [18]:
# aggregate rows-wise
sum_of_conda_downloads_50 = conda_downloads_50.sum(axis=1)
sum_of_conda_downloads_50

array([50, 50, 50, ..., 50, 50, 50])

In [19]:
# aggregate for probability
(sum_of_conda_downloads_50 == 50).mean()

0.8158

In [20]:
# 100 students?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_100 = np.random.choice([0, 1], size=(10_000, 100), p=[1/250, 249/250])
conda_downloads_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [21]:
# aggregate rows-wise
sum_of_conda_downloads_100 = conda_downloads_100.sum(axis=1)
sum_of_conda_downloads_100

array([100, 100,  99, ..., 100,  99, 100])

In [22]:
# aggregate for probability
(sum_of_conda_downloads_100 == 100).mean()

0.6642

In [23]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_150 = np.random.choice([0, 1], size=(10_000, 150), p=[1/250, 249/250])
conda_downloads_150

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [24]:
# aggregate rows-wise
sum_of_conda_downloads_150 = conda_downloads_150.sum(axis=1)
sum_of_conda_downloads_150

array([150, 150, 150, ..., 150, 149, 150])

In [25]:
# aggregate for probability
(sum_of_conda_downloads_150 < 150).mean()

0.4534

In [26]:
# How likely is it that 450 students all download anaconda without
# an issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads_450 = np.random.choice([0, 1], size=(10_000, 450), p=[1/250, 249/250])
conda_downloads_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [27]:
# aggregate rows-wise
sum_of_conda_downloads_450 = conda_downloads_450.sum(axis=1)
sum_of_conda_downloads_450

array([449, 449, 449, ..., 448, 448, 448])

In [29]:
# aggregate for probability
(sum_of_conda_downloads_450 == 450).mean()

0.1642

In [43]:
# 7. There's a 70% chance on any given day that there will be at
# least one food truck at Travis Park.
# However, you haven't seen a food truck there in 3 days.
# How unlikely is this?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_3_days = np.random.choice([0, 1], size=(10_000,3), p=[.3, .7])
food_truck_appearances_3_days

array([[1, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 1]])

In [44]:
# aggregate row-wise
sum_of_appearances_3_days = food_truck_appearances_3_days.sum(axis=1)
sum_of_appearances_3_days

array([3, 1, 1, ..., 1, 1, 2])

In [45]:
# aggregate for probability
(sum_of_appearances_3_days == 0).mean()

0.0262

In [47]:
# How likely is it that a food truck will show up sometime this week?

# represent data; no appearance = 0, appearance = 1
# create matrix
food_truck_appearances_week = np.random.choice([0, 1], size=(10_000,7), p=[.3, .7])
food_truck_appearances_week

array([[1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 0, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 0, 0]])

In [48]:
# aggregate row-wise
sum_of_appearances_week = food_truck_appearances_week.sum(axis=1)
sum_of_appearances_week

array([4, 5, 3, ..., 3, 6, 5])

In [54]:
# aggregate for probability
(sum_of_appearances_week > 0).mean()

0.9999

In [55]:
# 8. If 23 people are in the same room, what are the odds that two of them share a birthday?
# What if it's 20 people?
# 40?

# represent data; no share = 0, share = 1
# create matrix
birthday_in_common = np.random.choice([0, 1], size=(10_000, 23), p=[364/365, 1/365])
birthday_in_common

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [56]:
# aggregate by row
sum_of_birthday_in_common = birthday_in_common.sum(axis=1)
sum_of_birthday_in_common

array([0, 1, 0, ..., 0, 0, 0])

In [57]:
# aggregate for probability
(sum_of_birthday_in_common == 1).mean()

0.0594