In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How likely is it that you roll doubles when rolling two dice?
# represent data
# create matrix
die_rolls = pd.DataFrame(np.random.choice(range(1,7), size=(10_000, 2)))
die_rolls

0  1
0     1  5
1     3  5
2     3  5
3     1  4
4     2  4
...  .. ..
9995  2  2
9996  3  2
9997  1  6
9998  2  6
9999  5  2

[10000 rows x 2 columns]

In [3]:
# aggregate row-wise
die_rolls[0] == die_rolls[1]

0       False
1       False
2       False
3       False
4       False
        ...  
9995     True
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [4]:
# aggregate to get probability
(die_rolls[0] == die_rolls[1]).mean()

0.1586

In [5]:
# 2. If you flip 8 coins, what is the probability of getting exactly
# 3 heads? What is the probability of getting more than 3 heads?

# represent data; tails = 0, heads = 1
# create matrix
coin_flips = np.random.choice([0, 1], size=(10_000, 8))
coin_flips

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 1]])

In [6]:
# aggregate row-wise
sum_of_coin_flips = coin_flips.sum(axis=1)
sum_of_coin_flips

array([4, 5, 6, ..., 3, 3, 3])

In [7]:
# aggregate to get probability - exactly three
(sum_of_coin_flips == 3).mean()

0.218

In [8]:
# aggregate to get probability - greater than three
(sum_of_coin_flips > 3).mean()

0.6399

In [9]:
# 3. There are approximitely 3 web development cohorts
# for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a
# billboard, what are the odds that the two billboards I drive past
# both have data science students on them?

# represent data; web dev = 0, data sci = 1
# create matrix
cohorts = np.random.choice([0, 1], size=(10_000, 2), p=[3/4, 1/4])
cohorts

array([[0, 0],
       [0, 1],
       [1, 0],
       ...,
       [1, 0],
       [0, 0],
       [1, 0]])

In [10]:
# aggregate rows-wise
sum_of_cohorts = cohorts.sum(axis=1)
sum_of_cohorts

array([0, 1, 1, ..., 1, 0, 1])

In [11]:
# aggregate to get probability
(sum_of_cohorts == 2).mean()

0.0611

In [22]:
# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5)
# a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages,
# how likely is it that I will be able to buy some poptarts on
# Friday afternoon?

# represent data
# create matrix
poptarts = pd.DataFrame(np.random.normal(3, 1.5, size=(10_000, 5)).round())
poptarts.replace()

0    1    2    3    4
0     2.0 -0.0  5.0  0.0  3.0
1     4.0  1.0  4.0  2.0  1.0
2     7.0  5.0  3.0  1.0  3.0
3     4.0  6.0  3.0  3.0  2.0
4     3.0  7.0  3.0  2.0 -1.0
...   ...  ...  ...  ...  ...
9995  4.0  0.0  6.0  0.0  2.0
9996  4.0  3.0  4.0  3.0  2.0
9997  4.0  4.0  2.0  1.0  2.0
9998  1.0  1.0  6.0  2.0  5.0
9999  2.0  3.0  1.0  2.0  3.0

[10000 rows x 5 columns]

In [13]:
# aggregate rows-wise
sum_of_poptarts = poptarts.sum(axis=1)
sum_of_poptarts

array([14.66521446, 13.10523364,  9.3915353 , ..., 10.65671555,
       10.41287684, 16.427559  ])

In [14]:
# aggregate to get probability
(sum_of_poptarts <= 16).mean()

0.6175

In [15]:
# 5. Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

# represent data
# create matrix
men = np.random.normal(178, 8, size=(10_000))
women = np.random.normal(170, 6, size=(10_000))
# aggregate rows-wise
comparison = (women > men) == True
# aggregate for probability
comparison.mean()

0.2143

In [16]:
# 6. When installing anaconda on a student's computer,
# there's a 1 in 250 chance that the download is corrupted
# and the installation fails.
# What are the odds that after having 50 students download anaconda,
# no one has an installation issue?

# represent data; fail = 0, pass = 1
# create matrix
conda_downloads = np.random.choice([0, 1], size=(10_000, 50), p=(1/250, 249/250))
conda_downloads

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [17]:
# aggregate rows-wise


In [18]:
# 100 students?

In [19]:
# What is the probability that we observe an installation issue
# within the first 150 students that download anaconda?

# How likely is it that 450 students all download anaconda without
# an issue?